version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: demo_pod_app
      POSTGRES_PASSWORD: "YNqGO0SaPEELAyUrV_VMpCsQcEBZj3TC"
    volumes:
      - demo_pod_app_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "kD0FhaQBbGtjaFcJ1p9uVSjlTWSmyWmA"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  demo_pod_app_data:
